config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_scope :user do
    get 'users/:username', to: 'users/sessions#profile', as: 'user_profile'
    get 'users/:id/edit', to: 'users/registrations#edit', as: 'edit_user'
    get 'login', to: 'users/sessions#new', as: 'login'
    get 'register', to: 'users/registrations#new', as: 'register'
  end
  resources :posts do
    member do
      patch 'upvote', to: 'posts#upvote'
      patch 'downvote', to: 'posts#downvote'
    end
  end
  root to: "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  belongs_to :user
  belongs_to :Category
  def post_votes
    (self.get_upvotes.size - self.get_downvotes.size)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post
    else
      render :new
    end
  end

    def update
      if @post.update(post_params)
        redirect_to @post
      else
        render :edit
      end
    end

  def destroy
    @post.destroy
    redirect_to posts_url
  end

  def upvote
    if not @post.user.id == current_user.id
      @post.upvote_by current_user
      @post.user.point_up
      @post.user.save
      @post.user.points += 1
      redirect_to :back
    end
  end

  def downvote
    if not @post.user.id == current_user.id
      @post.downvote_by current_user
      @post.user.save
      @post.user.points -= 1
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <%= f.text_field :title, placeholder: "عنوان يصف الموضوع بشكل كافي" %>
  <%= f.text_area :content, placeholder: "محتوى الموضوع" %>
  <%= f.submit "نَشْر", class: "btn post_submit" %>
<% end %>

app/views/posts/downvote.js.erb
var avg = parseInt(<%= @post.post_votes %>);
var up = parseInt(<%= @post.get_upvotes.size %>);
var down = parseInt(<%= @post.get_downvotes.size %>);
$("#vote_avg_<%= @post.id %>").text(avg);
$("#vote_up_<%= @post.id %>").text(up);
$("#vote_down_<%= @post.id %>").text(down);

app/views/posts/edit.html.erb
<div class="container post_form white-box">
  <h3>تعديل الموضوع</h3>
  <%= render 'form', post: @post %>
  <%= link_to 'Back', posts_path, class: "btn" %>
</div>

app/views/posts/index.html.erb
<div class="body flex-column">
  <% @posts.each do |post| %>
    <div class="white-box post">
      <div class="title">
        <%= link_to post.title, post_path(post) %>
      </div>
      <div class="info flex-center-start">
        <div class="votes flex-center-around">
          <%= link_to upvote_post_path(post), method: :patch, remote: true, class: "upvote vote-box" do %>
            <svg class="icon-chevron-down upvote-icon sixteenth-px"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-chevron-down"></use></svg>
          <% end %>
          <div id="vote_avg_<%= post.id %>" class="vote-avg vote-box">
            <%= post.post_votes %>
          </div>
          <%= link_to downvote_post_path(post), method: :patch, remote: true, class: "downvote vote-box" do %>
            <svg class="icon-chevron-down sixteenth-px"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-chevron-down"></use></svg>
          <% end %>
        </div>
          <div class="username info-element">
            <%= image_tag (post.user.image_url or asset_path 'default-avatar.png'), width: "25px", height: "25px", class: "user_avatar" %>
            <%= link_to post.user.username, user_profile_path(post.user.username) %>
          </div>
          <div class="time-ago info-element">
            <svg class="icon-time sixteenth-px"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-time"></use></svg>
            <%= time_ago_in_arabic(post.created_at) %>
          </div>
          <div class="comments info-element">
            <svg class="icon-chat sixteenth-px"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-chat"></use></svg>
            23
          </div>
      </div>

    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container post_form white-box">
  <h3>موضوع جديد</h3>
  <%= render 'form', post: @post %>
</div

app/views/posts/show.html.erb
<div class="show-post">
  <div class="post-container white-box">
    <div class="post show-post">
      <div class="title"><%= link_to @post.title, post_path(@post) %></div>
      <div class="info flex-center-start">
        <div class="votes flex-center-around">
          <%= link_to upvote_post_path(@post), method: :patch, remote: true, class: "upvote vote-box" do %>
            <svg class="icon-chevron-down upvote-icon sixteenth-px"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-chevron-down"></use></svg>
            <span id="vote_up_<%= @post.id %>"><%= @post.get_upvotes.size %></span>
          <% end %>
          <div id="vote_avg_<%= @post.id %>" class="vote-avg vote-box">
            <%= @post.post_votes %>
          </div>
          <%= link_to downvote_post_path(@post), method: :patch, remote: true, class: "downvote vote-box" do %>
            <span id="vote_down_<%= @post.id %>">
              <%= @post.get_downvotes.size %>
            </span>
            <svg class="icon-chevron-down sixteenth-px"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-chevron-down"></use></svg>
          <% end %>
        </div>
        <div class="username info-element">
          <%= image_tag (@post.user.image_url or asset_path 'default-avatar.png'), width: "25px", height: "25px", class: "user_avatar" %>
          <%= link_to @post.user.username, user_profile_path(@post.user.username) %>
        </div>
        <div class="time-ago info-element">
          <svg class="icon-time sixteenth-px"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-time"></use></svg>
          <%= time_ago_in_arabic(@post.created_at) %>
        </div>
        <div class="comments info-element">
          <svg class="icon-chat sixteenth-px"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-chat"></use></svg>
          23
        </div>
        <%= link_to edit_post_path(@post), class: "edit info-element" do %>
          <svg class="icon-create sixteenth-px"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-create"></use></svg>
          تعديل
        <% end %>
        <%= link_to @post, :method => :delete, data: { confirm:  "هل أنت متأكد؟"}, class: "delete info-element" do %>
          <svg class="icon-delete sixteenth-px"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-delete"></use></svg>
          حذف
        <% end %>
      </div>
      <div id="md-content" class="post-content">
        <%= markdown @post.content %>
      </div>
    </div>
  </div>
</div>

app/views/posts/upvote.js.erb
var avg = parseInt(<%= @post.post_votes %>);
var up = parseInt(<%= @post.get_upvotes.size %>);
var down = parseInt(<%= @post.get_downvotes.size %>);
$("#vote_avg_<%= @post.id %>").text(avg);
$("#vote_up_<%= @post.id %>").text(up);
$("#vote_down_<%= @post.id %>").text(down);