config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  devise_scope :user do
    get 'users/:username', to: 'users/sessions#profile', as: 'user_profile'
    get 'users/:id/edit', to: 'users/registrations#edit', as: 'edit_user'
    get 'login', to: 'users/sessions#new', as: 'login'
    get 'register', to: 'users/registrations#new', as: 'register'
  end
  resources :posts do
    member do
      patch 'upvote', to: 'posts#upvote'
      patch 'downvote', to: 'posts#downvote'
    end
  end
  root to: "posts#index"
end

app/views/layouts/_header.html.erb
<header id="Header">
  <div class="header-elements">
    <%= link_to root_path, class: "logo" do %>
      نقاشات<span> I/O </span>
    <% end %>
    <% if user_signed_in? %>
      <div class="side-elements">
        <div class="user-functions flex-center-around">
          <svg class="icon-search function"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-search"></use></svg>
          <%= link_to new_post_path, class: "add-post function" do %>
            <svg class="icon-add-circle"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-add-circle"></use></svg>
          <% end %>
          <svg class="icon-notifications function"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-notifications"></use></svg>
          <svg class="icon-mail function"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-mail"></use></svg>
        </div>
        <div class="user-info flex-center-around">
          <%= link_to current_user.username, user_profile_path(current_user.username), class: "user-name" %>
          <img src="<%= current_user.image_url or asset_path 'default-avatar.png' %>" class="user-avatar" alt="user-avatar" width="32" height="32" />
          <svg class="icon-chevron-down sixteenth-px dropdown-btn" onclick="document.getElementById('user_settings').classList.toggle('collapsed');"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-chevron-down"></use></svg>
        </div>
      </div>
      <div id="user_settings" class="collapsed">
        <%= link_to 'تعديل الملف الشخصي', edit_user_path(current_user) %>
        <%= link_to 'تسجل الخروج', destroy_user_session_path, method: :delete %>
      </div>
    <% else %>
      <div class="side-elements">
        <%= link_to "دخول", login_path, class: "btn btn-dark-shadow header-btn" %>
        <%= link_to "حساب جديد", register_path, class: "btn btn-dark-shadow header-btn" %>
      </div>
    <% end %>
          </div>
  <nav id="navigation-bar">
    <div class="container flex-center-around">
      <div class="element active">الأكثر شيوعاً</div>
      <div class="element">الأحدث</div>
      <div class="element">إكتشف</div>
      <div class="element">الأفضل</div>
    </div>
  </nav>
</header>

app/views/layouts/_sidebar.html.erb
<div class="sidebar flex-column">
  <div class="block">
    <%= link_to new_post_path,class: "btn btn-block" do %>
        <svg class="icon-add sixteenth-px"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-add"></use></svg>
        <span>إضافة نقاش</span>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arabia</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1,user-scalable=no" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="//fonts.googleapis.com/css?family=Cairo:400,700" rel="stylesheet" />
    <!-- <link href="https://fonts.googleapis.com/css?family=Amiri|Lalezar&subset=arabic" rel="stylesheet" /> -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div id="Content" class="container">
      <%= yield %>
    </div>
  </body>
</html>